[database.identity_db]
type = "postgre"
hostname = "postgres"
name = "testdb"
username = "wso2admin"
password = "wso2admin"
port = "5432"

[database.shared_db]
type = "postgre"
hostname = "postgres"
name = "testdb"
username = "wso2admin"
password = "wso2admin"
port = "5432"

[database.consent_db]
type = "postgre"
hostname = "postgres"
name = "testdb"
username = "wso2admin"
password = "wso2admin"
port = "5432"

[database.identity_db.pool_options]
maxActive = "80"
maxWait = "360000"
minIdle = "5"
testOnBorrow = true
validationQuery = "SELECT 1"
validationInterval = "30000"
defaultAutoCommit = false
commitOnReturn = true

# Esto es la configuracion que viene por defecto de wso2 container
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

#[database.identity_db]
#type = "h2"
#url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
#username = "wso2carbon"
#password = "wso2carbon"

#[database.shared_db]
#type = "h2"
#url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
#username = "wso2carbon"
#password = "wso2carbon"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"
type="JKS"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

# The KeyStore which is used for encrypting/decrypting internal data. By default the primary keystore is used as the internal keystore.
#enabled = true
#api_url = "https://www.google.com/recaptcha/api.js"
#verify_url = "https://www.google.com/recaptcha/api/siteverify"
#site_key = ""
#secret_key = ""

# SMTP email sender settings.
#[output_adapter.email]
#from_address= "abcd@gmail.com"
#username= "abcd"
#password= "xxxx"
#hostname= "smtp.gmail.com"
#port= 587