services:
  postgres:
    image: postgres:13.22-alpine3.21
    container_name: postgres_wso2is
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - wso2net

  wso2is:
    image: wso2/wso2is:7.0.0
    container_name: wso2is_7_v2
    depends_on:
      - postgres
    ports:
      - "9443:9443"
    volumes:
      - ./postgresql-42.7.8.jar:/home/wso2carbon/wso2is-7.0.0/repository/components/lib/postgresql.jar
      - ./deployment.toml:/home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
    networks:
      - wso2net

volumes:
  pgdata:

networks:
  wso2net:
